In [2]:
import pandas as pd

In [3]:
yelp_final_df=pd.read_csv('yelp_final_df2.csv')

In [4]:
yelp_final_df.head(2)

,review_id,user_id,business_id,name,text,address,city,state,postal_code,latitude,longitude,attributes,categories,Sentiment,Review Rating,Business Rating,Date,Year,Month
0,S337tATeouQJdoPYyir29w,2mxBNBeFrgDszqGS5tdEHA,d_L-rfS1vT3JMzgCUGtiow,Border Grill,Pick any meat on the planet and the chef will ...,3950 S Las Vegas Blvd,Las Vegas,NV,89119.0,36.090067,-115.176973,"{'WiFi': ""u'free'"", 'RestaurantsTakeOut': 'Tru...","Breakfast & Brunch, Restaurants, Tapas/Small P...",Positive,5.0,4.0,2016-07-25 03:57:19,2016,7
1,j3vP8537KHvoXNHQIr3haA,Z_HE_KKT7N-WddPTzUQC7A,jScBTQtdAt-8RshaiBEHgw,Served,"Party of 3 ordered the fish tacos, pork belly ...","1770 W Horizon Ridge, Ste 100",Henderson,NV,89012.0,36.010745,-115.064803,"{'DriveThru': 'False', 'RestaurantsAttire': ""'...","Ethnic Food, American (New), Burgers, Food, Re...",Positive,5.0,4.5,2018-05-28 20:56:05,2018,5

In [5]:
yelp_final_df['Sentiment'].value_counts()

Positive    90207
Negative    39450
Name: Sentiment, dtype: int64

In [6]:
yelp_positive=yelp_final_df.loc[yelp_final_df['Sentiment']=='Positive',:]

In [7]:
yelp_positive.shape

(90207, 19)

In [8]:
import nltk
nltk.download('stopwords')

import string
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/juliusmagsino/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [9]:
pos_text=yelp_positive['text']

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
count_vectorizer = CountVectorizer(ngram_range=(1, 1),  
                                   stop_words={'a','about','above','after','again','against','ain','all','am',
                                               'an','and','any','are','aren',"aren't",'as','at','be','because',
                                               'been','before','being','below','between','both','but','by','can',
                                               'couldn',"couldn't",'d','did','didn',"didn't",'do','does','doesn',
                                               "doesn't",'doing','don',"don't",'down','during','each','few','for',
                                               'from','further','had','hadn',"hadn't",'has','hasn',"hasn't",'have',
                                               'haven',"haven't",'having','he','her','here','hers','herself','him',
                                               'himself','his','how','i','if','in','into','is','isn',"isn't",'it',
                                               "it's",'its','itself','just','ll','m','ma','me','mightn',"mightn't",
                                               'more','most','mustn',"mustn't",'my','myself','needn',"needn't",'no',
                                               'nor','not','now','o','of','off','on','once','only','or','other','our',
                                               'ours','ourselves','out','over','own','re','s','same','shan',"shan't",
                                               'she',"she's",'should',"should've",'shouldn',"shouldn't",'so','some',
                                               'such','t','than','that',"that'll",'the','their','theirs','them',
                                               'themselves','then','there','these','they','this','those','through',
                                               'to','too','under','until','up','ve','very','was','wasn',"wasn't",
                                               'we','were','weren',"weren't",'what','when','where','which','while',
                                               'who','whom','why','will','with','won',"won't",'wouldn',"wouldn't",
                                               'y','you',"you'd","you'll","you're","you've",'your','yours','yourself',
                                               'yourselves', 'mexican', 'las', 'vegas'}, 
                                               token_pattern="\\b[a-z][a-z]+\\b")

count_vectorizer.fit(pos_text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None,
                stop_words={'a', 'about', 'above', 'after', 'again', 'against',
                            'ain', 'all', 'am', 'an', 'and', 'any', 'are',
                            'aren', "aren't", 'as', 'at', 'be', 'because',
                            'been', 'before', 'being', 'below', 'between',
                            'both', 'but', 'by', 'can', 'couldn', "couldn't", ...},
                strip_accents=None, token_pattern='\\b[a-z][a-z]+\\b',
                tokenizer=None, vocabulary=None)

In [13]:
doc_word = count_vectorizer.transform(pos_text)

In [15]:
pd.DataFrame(doc_word.toarray(),columns=count_vectorizer.get_feature_names()).head(2)

,aa,aaa,aaaa,aaaaaaaawesome,aaaaaaamazing,aaaaaand,aaaaamaaazing,aaaaamazing,aaaaand,aaaahmazzzing,...,zusanna,zutaten,zway,zwei,zweifel,zwiebeln,zzz,zzzs,zzzzs,zzzzzzzz
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
from sklearn.decomposition import NMF
nmf_model = NMF(6)
doc_topic = nmf_model.fit_transform(doc_word)

In [17]:
nmf_model.components_.shape

(6, 46375)

In [19]:
topic_word = pd.DataFrame(nmf_model.components_.round(3),
             index = ["component_1","component_2","component_3","component_4","component_5","component_6"],
             columns = count_vectorizer.get_feature_names())
topic_word

,aa,aaa,aaaa,aaaaaaaawesome,aaaaaaamazing,aaaaaand,aaaaamaaazing,aaaaamazing,aaaaand,aaaahmazzzing,...,zusanna,zutaten,zway,zwei,zweifel,zwiebeln,zzz,zzzs,zzzzs,zzzzzzzz
component_1,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.001,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
component_2,0.0,0.000,0.0,0.0,0.0,0.002,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
component_3,0.0,0.001,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
component_4,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
component_5,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
component_6,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
def display_topics(model, feature_names, no_top_words, topic_names=None):
    for ix, topic in enumerate(model.components_):
        if not topic_names or not topic_names[ix]:
            print("\nTopic ", ix)
        else:
            print("\nTopic: '",topic_names[ix],"'")
        print(", ".join([feature_names[i]
                        for i in topic.argsort()[:-no_top_words - 1:-1]]))

In [21]:
display_topics(nmf_model, count_vectorizer.get_feature_names(), 10)

Topic  0
like, one, ordered, chicken, time, salsa, would, also, menu, restaurant

Topic  1
tacos, taco, asada, carne, pastor, meat, al, get, el, best

Topic  2
food, service, restaurant, best, amazing, always, delicious, fast, friendly, staff

Topic  3
good, really, pretty, salsa, service, chips, nice, got, also, little

Topic  4
great, service, back, amazing, friendly, awesome, definitely, atmosphere, staff, drinks

Topic  5
place, love, go, try, like, get, always, amazing, burrito, best

In [24]:
H = pd.DataFrame(doc_topic.round(5),
             columns = ["component_1","component_2","component_3","component_4","component_5","component_6"])
H.head()

,component_1,component_2,component_3,component_4,component_5,component_6
0,0.00733,0.05744,0.00000,0.00000,0.05758,0.00000
1,0.06408,0.07702,0.04691,0.05627,0.07428,0.00000
2,0.06233,0.00000,0.04791,0.00497,0.05570,0.06873
3,0.02638,0.00400,0.00397,0.00000,0.00000,0.00476
4,0.02958,0.00716,0.00946,0.00303,0.07065,0.00217

In [27]:
yelp_positive.reset_index(drop=True,inplace=True)

In [36]:
merged_pos=yelp_positive.merge(H, left_index=True, right_index=True)

In [37]:
merged_pos.shape

(90207, 25)

In [38]:
merged_pos

,review_id,user_id,business_id,name,text,address,city,state,postal_code,latitude,...,Business Rating,Date,Year,Month,component_1,component_2,component_3,component_4,component_5,component_6
0,S337tATeouQJdoPYyir29w,2mxBNBeFrgDszqGS5tdEHA,d_L-rfS1vT3JMzgCUGtiow,Border Grill,Pick any meat on the planet and the chef will ...,3950 S Las Vegas Blvd,Las Vegas,NV,89119.0,36.090067,...,4.0,2016-07-25 03:57:19,2016,7,0.00733,0.05744,0.00000,0.00000,0.05758,0.00000
1,j3vP8537KHvoXNHQIr3haA,Z_HE_KKT7N-WddPTzUQC7A,jScBTQtdAt-8RshaiBEHgw,Served,"Party of 3 ordered the fish tacos, pork belly ...","1770 W Horizon Ridge, Ste 100",Henderson,NV,89012.0,36.010745,...,4.5,2018-05-28 20:56:05,2018,5,0.06408,0.07702,0.04691,0.05627,0.07428,0.00000
2,EedJ77WTwkytYhAR-PVMKQ,piYjHlLZQCtg9Q1QT0Lvbw,gOOfBSBZlffCkQ7dr7cpdw,Chica,Five stars! I highly recommend this place if y...,"3355 South Las Vegas Blvd, Ste 106",Las Vegas,NV,89109.0,36.122690,...,4.5,2018-04-27 18:59:14,2018,4,0.06233,0.00000,0.04791,0.00497,0.05570,0.06873
3,kN7QMpXNT38NeeesQ6zYUQ,U6tZwpRVjUfx-fwDbMAlPA,lVfZ2AaYRYHCFenUMQna8g,Super B Burrito,Oooh momma!\nThe flavor is strong with this on...,8899 S Eastern Ave,Las Vegas,NV,89123.0,36.028098,...,4.0,2015-10-07 20:52:28,2015,10,0.02638,0.00400,0.00397,0.00000,0.00000,0.00476
4,LQ4seKEnmMK5PYKtFcaT3A,9SqPSd2HnDJIM3v4_j9LYA,SVGApDPNdpFlEjwRQThCxA,Juan's Flaming Fajitas & Cantina,I don't normally say things are the best but t...,"9640 W Tropicana, Ste 101",Las Vegas,NV,89147.0,36.100509,...,4.5,2014-10-11 08:23:56,2014,10,0.02958,0.00716,0.00946,0.00303,0.07065,0.00217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90202,Jj1YtYCkBcT0VOLOVphP8A,7Q6nBHl6NJ9gbJ900FkkAg,MyTsAeShB9pcWP84GSTAdw,KoMex Fusion,"Like most places in Vegas, KoMex is in a rando...",4155 S Buffalo Dr,Las Vegas,NV,89147.0,36.113268,...,4.5,2014-08-08 00:05:30,2014,8,0.08716,0.09663,0.00000,0.10361,0.04211,0.01125
90203,ys0McWHojMRp353JD4f5dQ,t0JsM8unOz4Rx3gRwK_ZDQ,MZRqxvBkJLjKcoOjNz7yLA,Carlos'n Charlie's,Ordered shrimp quesadillas...there was maybe 5...,3555 S Las Vegas Blvd,Las Vegas,NV,89109.0,36.116418,...,2.5,2016-03-05 04:41:52,2016,3,0.03389,0.00060,0.00000,0.00014,0.00466,0.00000
90204,6XxuPW35avv8MixuPWUNpg,n28qz1Lt9ROormO7eCooOg,0QSnurP5Ibor2zepJmEIlw,Tacos La Mexicana,"Carne asada nachos, hard shell tacos, mulitas,...","3555 S Durango Dr, Ste B101",Las Vegas,NV,89147.0,36.124897,...,4.0,2016-05-06 03:53:03,2016,5,0.00000,0.06980,0.00000,0.04957,0.16025,0.00845
90205,UG4aLPKajJJ6gMXYPXKoPA,GjTGlqJzI4EHenN5TBNrYw,a192hdM0_UVCYLwPJv1Qwg,Casa Don Juan - Downtown,My first time here tonight and we got seated i...,1204 S Main St,Las Vegas,NV,89104.0,36.157156,...,4.0,2017-08-10 10:05:38,2017,8,0.06302,0.11075,0.05303,0.04912,0.01371,0.00236
90206,zwzO3yPdGbdgGy3-XQ0SWg,PFiIECX8wuvi7P-1mCvIjA,a192hdM0_UVCYLwPJv1Qwg,Casa Don Juan - Downtown,"Off the grid Mexican in Vegas. Very tasty, qua...",1204 S Main St,Las Vegas,NV,89104.0,36.157156,...,4.0,2018-11-13 21:15:20,2018,11,0.00000,0.00000,0.04594,0.00060,0.00361,0.05600

In [39]:
merged_pos.columns

Index(['review_id', 'user_id', 'business_id', 'name', 'text', 'address',
       'city', 'state', 'postal_code', 'latitude', 'longitude', 'attributes',
       'categories', 'Sentiment', 'Review Rating', 'Business Rating', 'Date',
       'Year', 'Month', 'component_1', 'component_2', 'component_3',
       'component_4', 'component_5', 'component_6'],
      dtype='object')

In [40]:
merged_pos.to_csv('Yelp_Pos_Topics.csv',index=False)